In [11]:
w1,w2,w3 =0.3, 0.2,0.5

In [7]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [15]:
weights = [w1,w2,w3]

In [3]:
def crop_yield(location, weights):
    return sum(x * w for x,w in zip(location,weights))

In [17]:
crop_yield(johto, weights)

76.9

In [4]:
import numpy as np

Numpy Arrays can be created using the np.array function

In [28]:
kanto=np.array([73,67,43])

In [30]:
kanto

array([73, 67, 43])

In [32]:
weights = np.array([w1,w2,w3])

In [34]:
weights

array([0.3, 0.2, 0.5])

In [36]:
np.dot(kanto, weights)

56.8

In [38]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----

In [40]:
climate_data  = np.array([[73, 67, 43],[91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]])

In [42]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [44]:
climate_data.shape

(5, 3)

In [46]:
weights.shape

(3,)

In [48]:
weights.dtype

dtype('float64')

In [50]:
climate_data.dtype

dtype('int64')

In [52]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [56]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [60]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 'climate.txt')


('climate.txt', <http.client.HTTPMessage at 0x13cd46dd0>)

In [62]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [64]:
climate_data.shape

(10000, 3)

In [66]:
yields = climate_data @ weights

In [68]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [70]:
yields.shape

(10000,)

In [72]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis=1) 

In [74]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [76]:
np.savetxt('climate_results.txt',climate_results,fmt='%.2f',header='temperature,rainfall,humidity,yield_apples',comments='')

# Arithmetic Operations and Broadcasting

In [79]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [81]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [83]:
arr2 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18,  2,  4,  6]])

# Array Indexing and Slicing

In [88]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr3.shape

(3, 2, 4)

In [96]:
# single element
arr3[0,0,0]

11.0

In [100]:
# subarray using ranges
arr3[1:, 0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [104]:
np.random.rand(5,3)

array([[0.35106183, 0.37923929, 0.84497548],
       [0.75674634, 0.95269368, 0.29303387],
       [0.54258169, 0.84855153, 0.88551621],
       [0.09179358, 0.25252357, 0.53958444],
       [0.26530606, 0.36678306, 0.23105135]])

In [106]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [116]:
np.random.randn(4,5)

array([[-0.97372551, -0.00831776,  0.01646385, -0.37044362, -0.14791769],
       [ 1.67415536, -0.83701257, -0.77191277, -1.20085094,  0.71325765],
       [ 0.07884225,  0.25310028,  1.96727368, -0.15300976, -1.04382757],
       [-0.21796074,  1.27322396, -1.07360759, -0.66441874,  1.46681045]])

In [118]:
np.full([2,3],42)


array([[42, 42, 42],
       [42, 42, 42]])

In [30]:
np.arange(10,90,3).reshape


(27,)

# Interacting with the OS and filesystem

In [2]:
import os

In [4]:
os.cwd()

AttributeError: module 'os' has no attribute 'cwd'

In [6]:
os.getcwd()

'/Users/oluwademilade/Desktop/Code/python/Data/Data-initium'

In [8]:
help(os.listdir)

Help on built-in function listdir in module posix:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.

