In [11]:
w1,w2,w3 =0.3, 0.2,0.5

In [7]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [15]:
weights = [w1,w2,w3]

In [3]:
def crop_yield(location, weights):
    return sum(x * w for x,w in zip(location,weights))

In [17]:
crop_yield(johto, weights)

76.9

In [4]:
import numpy as np

Numpy Arrays can be created using the np.array function

In [28]:
kanto=np.array([73,67,43])

In [30]:
kanto

array([73, 67, 43])

In [32]:
weights = np.array([w1,w2,w3])

In [34]:
weights

array([0.3, 0.2, 0.5])

In [36]:
np.dot(kanto, weights)

56.8

In [38]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----

In [40]:
climate_data  = np.array([[73, 67, 43],[91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]])

In [42]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [44]:
climate_data.shape

(5, 3)

In [46]:
weights.shape

(3,)

In [48]:
weights.dtype

dtype('float64')

In [50]:
climate_data.dtype

dtype('int64')

In [52]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [56]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [60]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 'climate.txt')


('climate.txt', <http.client.HTTPMessage at 0x13cd46dd0>)

In [62]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [64]:
climate_data.shape

(10000, 3)

In [66]:
yields = climate_data @ weights

In [68]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [70]:
yields.shape

(10000,)

In [72]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis=1) 

In [74]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [76]:
np.savetxt('climate_results.txt',climate_results,fmt='%.2f',header='temperature,rainfall,humidity,yield_apples',comments='')

# Arithmetic Operations and Broadcasting

In [79]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [81]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [83]:
arr2 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18,  2,  4,  6]])

# Array Indexing and Slicing

In [88]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr3.shape

(3, 2, 4)

In [96]:
# single element
arr3[0,0,0]

11.0

In [100]:
# subarray using ranges
arr3[1:, 0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [104]:
np.random.rand(5,3)

array([[0.35106183, 0.37923929, 0.84497548],
       [0.75674634, 0.95269368, 0.29303387],
       [0.54258169, 0.84855153, 0.88551621],
       [0.09179358, 0.25252357, 0.53958444],
       [0.26530606, 0.36678306, 0.23105135]])

In [106]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [116]:
np.random.randn(4,5)

array([[-0.97372551, -0.00831776,  0.01646385, -0.37044362, -0.14791769],
       [ 1.67415536, -0.83701257, -0.77191277, -1.20085094,  0.71325765],
       [ 0.07884225,  0.25310028,  1.96727368, -0.15300976, -1.04382757],
       [-0.21796074,  1.27322396, -1.07360759, -0.66441874,  1.46681045]])

In [118]:
np.full([2,3],42)


array([[42, 42, 42],
       [42, 42, 42]])

In [30]:
np.arange(10,90,3).reshape


(27,)

# Interacting with the OS and filesystem

In [5]:
import os

In [59]:
os.getcwd()

'/Users/oluwademilade/Desktop/Code/python/Data/Data-initium'

In [6]:
os.getcwd()

'/Users/oluwademilade/Desktop/Code/python/Data/Data-initium'

In [8]:
help(os.listdir)

Help on built-in function listdir in module posix:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [7]:
os.listdir('.')

['numpy_basics.ipynb',
 'climate.txt',
 '.gitignore',
 '.ipynb_checkpoints',
 '.git',
 'climate_results.txt']

In [11]:
help(os.makedirs)

Help on function makedirs in module os:

makedirs(name, mode=511, exist_ok=False)
    makedirs(name [, mode=0o777][, exist_ok=False])
    
    Super-mkdir; create a leaf directory and all intermediate ones.  Works like
    mkdir, except that any intermediate path segment (not just the rightmost)
    will be created if it does not exist. If the target directory already
    exists, raise an OSError if exist_ok is False. Otherwise no exception is
    raised.  This is recursive.



In [15]:
os.makedirs('./data', exist_ok=True)

In [19]:
'data' in os.listdir('.')

True

In [21]:
os.listdir('./data')

[]

In [29]:
url1 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'
url2 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans2.txt'
url3 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans3.txt'

In [23]:
from urllib.request import urlretrieve

In [31]:
urlretrieve(url1, './data/loans1.txt')
urlretrieve(url2, './data/loans2.txt')
urlretrieve(url3, './data/loans3.txt')

('./data/loans3.txt', <http.client.HTTPMessage at 0x13545e0d0>)

In [33]:
os.listdir('./data')

['loans2.txt', 'loans3.txt', 'loans1.txt']

# Reading from a file 

In [36]:
file1 = open('./data/loans1.txt', mode='r')

In [38]:
file_content =file1.read()

In [44]:
print(file_content)

amount,duration,rate,down_payment
100000,36,0.08,20000
200000,12,0.1,
628400,120,0.12,100000
4637400,240,0.06,
42900,90,0.07,8900
916000,16,0.13,
45230,48,0.08,4300
991360,99,0.08,
423000,27,0.09,47200


In [42]:
file1.close()

In [50]:
with open('./data/loans1.txt', 'r') as file2:
    file_content = file2.read()
    print(file_content)

amount,duration,rate,down_payment
100000,36,0.08,20000
200000,12,0.1,
628400,120,0.12,100000
4637400,240,0.06,
42900,90,0.07,8900
916000,16,0.13,
45230,48,0.08,4300
991360,99,0.08,
423000,27,0.09,47200


# Reading files as lines

In [55]:
with open('./data/loans3.txt', 'r') as file3:
    file3_content = file3.readlines()
    print(file3_content)

['amount,duration,rate,down_payment\n', '45230,48,0.07,4300\n', '883000,16,0.14,\n', '100000,12,0.1,\n', '728400,120,0.12,100000\n', '3637400,240,0.06,\n', '82900,90,0.07,8900\n', '316000,16,0.13,\n', '15230,48,0.08,4300\n', '991360,99,0.08,\n', '323000,27,0.09,4720010000,36,0.08,20000\n', '528400,120,0.11,100000\n', '8633400,240,0.06,\n', '12900,90,0.08,8900']


In [57]:
file3_content[0].strip()

'amount,duration,rate,down_payment'

In [63]:
def parse_headers(header_line):
    return header_line.strip().split(',')

In [65]:
parse_headers(file3_content[0])

['amount', 'duration', 'rate', 'down_payment']

In [83]:
def parse_values(data_line):
    return [float(item) for item in data_line.strip().split(',') if item != '']

In [79]:
parse_values(file3_content[1])

[45230.0, 48.0, 0.07, 4300.0]

In [73]:
file3_content[1]

'45230,48,0.07,4300\n'

In [85]:
parse_values(file3_content[2])

[883000.0, 16.0, 0.14]

In [109]:
def create_dict_item(value,header):
    return {header:value for (value,header) in zip(value,header)}

In [143]:
create_dict_item(parse_values(file3_content[3]), parse_headers(file3_content[0]))

{'amount': 100000.0, 'duration': 12.0, 'rate': 0.1}

In [155]:
def read_csv(path):
    with open(path,'r') as f:
        
        lines = f.readlines()
        headers = parse_headers(lines[0])
        
        result = [create_dict_item(parse_values(data_line), headers) for data_line in lines[1:]]
        return result

In [157]:
read_csv('./data/loans3.txt')

[{'amount': 45230.0, 'duration': 48.0, 'rate': 0.07, 'down_payment': 4300.0},
 {'amount': 883000.0, 'duration': 16.0, 'rate': 0.14},
 {'amount': 100000.0, 'duration': 12.0, 'rate': 0.1},
 {'amount': 728400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0},
 {'amount': 3637400.0, 'duration': 240.0, 'rate': 0.06},
 {'amount': 82900.0, 'duration': 90.0, 'rate': 0.07, 'down_payment': 8900.0},
 {'amount': 316000.0, 'duration': 16.0, 'rate': 0.13},
 {'amount': 15230.0, 'duration': 48.0, 'rate': 0.08, 'down_payment': 4300.0},
 {'amount': 991360.0, 'duration': 99.0, 'rate': 0.08},
 {'amount': 323000.0,
  'duration': 27.0,
  'rate': 0.09,
  'down_payment': 4720010000.0},
 {'amount': 528400.0,
  'duration': 120.0,
  'rate': 0.11,
  'down_payment': 100000.0},
 {'amount': 8633400.0, 'duration': 240.0, 'rate': 0.06},
 {'amount': 12900.0, 'duration': 90.0, 'rate': 0.08, 'down_payment': 8900.0}]

In [159]:
import math

def loan_emi(amount, duration, rate, down_payment=0):
    loan_amount = amount - down_payment

    try:
        emi= loan_amount * rate * ((1+rate)**duration) / (((1+rate)**duration)-1)
    except ZeroDivisionError:
        emi = loan_amount / duration

    emi= math.ceil(emi)
    return emi

In [197]:
loans1= read_csv('./data/loans1.txt')
loans1

[{'amount': 100000.0, 'duration': 36.0, 'rate': 0.08, 'down_payment': 20000.0},
 {'amount': 200000.0, 'duration': 12.0, 'rate': 0.1},
 {'amount': 628400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0},
 {'amount': 4637400.0, 'duration': 240.0, 'rate': 0.06},
 {'amount': 42900.0, 'duration': 90.0, 'rate': 0.07, 'down_payment': 8900.0},
 {'amount': 916000.0, 'duration': 16.0, 'rate': 0.13},
 {'amount': 45230.0, 'duration': 48.0, 'rate': 0.08, 'down_payment': 4300.0},
 {'amount': 991360.0, 'duration': 99.0, 'rate': 0.08},
 {'amount': 423000.0, 'duration': 27.0, 'rate': 0.09, 'down_payment': 47200.0}]

In [209]:
loans1=[{**loan, 'emi':loan_emi(loan['amount'], loan['duration'], loan['rate']/12,loan.get('down_payment',0))} for loan in loans1]
loans1

[{'amount': 100000.0,
  'duration': 36.0,
  'rate': 0.08,
  'down_payment': 20000.0,
  'emi': 2507},
 {'amount': 200000.0, 'duration': 12.0, 'rate': 0.1, 'emi': 17584},
 {'amount': 628400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0,
  'emi': 7582},
 {'amount': 4637400.0, 'duration': 240.0, 'rate': 0.06, 'emi': 33224},
 {'amount': 42900.0,
  'duration': 90.0,
  'rate': 0.07,
  'down_payment': 8900.0,
  'emi': 487},
 {'amount': 916000.0, 'duration': 16.0, 'rate': 0.13, 'emi': 62664},
 {'amount': 45230.0,
  'duration': 48.0,
  'rate': 0.08,
  'down_payment': 4300.0,
  'emi': 1000},
 {'amount': 991360.0, 'duration': 99.0, 'rate': 0.08, 'emi': 13712},
 {'amount': 423000.0,
  'duration': 27.0,
  'rate': 0.09,
  'down_payment': 47200.0,
  'emi': 15428}]

In [222]:
def compute_emi(loans):
    loans = [{**loan, 'emi':loan_emi(loan['amount'], loan['duration'], loan['rate']/12, loan.get('down_payment',0))} for loan in loans]
    return loans

# Writing to Files

In [230]:
loans2 = read_csv('./data/loans2.txt')


In [236]:
loans2=compute_emi(loans2)

In [238]:
loans2

[{'amount': 828400.0,
  'duration': 120.0,
  'rate': 0.11,
  'down_payment': 100000.0,
  'emi': 10034},
 {'amount': 4633400.0, 'duration': 240.0, 'rate': 0.06, 'emi': 33196},
 {'amount': 42900.0,
  'duration': 90.0,
  'rate': 0.08,
  'down_payment': 8900.0,
  'emi': 504},
 {'amount': 983000.0, 'duration': 16.0, 'rate': 0.14, 'emi': 67707},
 {'amount': 15230.0,
  'duration': 48.0,
  'rate': 0.07,
  'down_payment': 4300.0,
  'emi': 262}]

In [246]:
with open('./data/loans2.txt', 'w') as file:
    [file.write('{},{},{},{},{}\n'.format(loan['amount'],loan['duration'],loan['rate'],loan.get('down_payment',0),loan['emi'])) for loan in loans2]

In [248]:
with  open('./data/loans2.txt', 'r') as file2:
    print(file2.read())

828400.0,120.0,0.11,100000.0,10034
4633400.0,240.0,0.06,0,33196
42900.0,90.0,0.08,8900.0,504
983000.0,16.0,0.14,0,67707
15230.0,48.0,0.07,4300.0,262



In [250]:
def write_csv(items,path):
    with open(path, 'w') as file:
        if len(items) == 0:
            return
        headers = list(item[0].keys())
        file.write(','.join(headers)+'\n')

        for item in items:
            file.write(','.join([str(item.get(header,"")) for header in headers])+ "\n")